# Generated by Django 6.0.6 on 2026-06-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='panorama_image',
            field=models.ImageField(blank=True, help_text='360° panoramic image for VR viewer', null=True, upload_to='places/panorama/'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(choices=[('dermatology', 'Dermatology'), ('rheumatology', 'Rheumatology'), ('physiotherapy', 'Physiotherapy'), ('orthopedics', 'Orthopedics'), ('respiratory', 'Respiratory Medicine'), ('balneotherapy', 'Balneotherapy'), ('hydrotherapy', 'Hydrotherapy'), ('naturopathy', 'Naturopathic Medicine'), ('general', 'General Medicine')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='e.g. Professor, Consultant', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('bio_ar', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('years_experience', models.IntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('available_days', models.CharField(blank=True, help_text='e.g. Sun,Mon,Tue,Wed', max_length=200)),
                ('available_hours', models.CharField(blank=True, help_text='e.g. 9:00 AM - 5:00 PM', max_length=100)),
                ('rating', models.FloatField(default=4.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('places', models.ManyToManyField(blank=True, limit_choices_to={'place_type': 'medical'}, related_name='doctors', to='store.place')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='Describe your symptoms')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='store.doctor')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Anonymized or with consent', max_length=100)),
                ('condition', models.CharField(max_length=200)),
                ('treatment', models.TextField()),
                ('outcome', models.TextField(blank=True)),
                ('duration_weeks', models.IntegerField(default=1)),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='store.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'user')},
            },
        ),
    ]
